- name: Install necessary packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker.io
      - conntrack

- name: Ensure Docker is started and enabled at boot
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Télécharger Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Installer kubectl
  get_url:
    url: https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Installer Helm
  get_url:
    url: https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz

- name: Décompresser Helm
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp
    remote_src: yes

- name: Déplacer les binaires de Helm
  command: mv /tmp/linux-amd64/helm /usr/local/bin/helm

- name: Install Kompose
  get_url:
    url: https://github.com/kubernetes/kompose/releases/download/v1.26.0/kompose-linux-amd64
    dest: /usr/local/bin/kompose
    mode: '0755'

