- name: Clone repository
  git:
    repo: 'https://github.com/humanWasHere/projet_devops_b3'
    dest: '/home/usr/project'
    clone: yes
    update: yes

- name: Build images
  shell: docker build -t angular-app:latest /home/usr/project/.

- name: Load image in minikube
  shell: minikube image load angular-app:latest
  become: yes
  become_user: usr

- name: Convert docker-compose.yml to Kubernetes configs
  shell: kompose convert -f /home/usr/project/docker-compose.yml -o /home/usr/project/k8s

- name: Assurer que imagePullPolicy est IfNotPresent pour tous les conteneurs
  lineinfile:
    path: /home/usr/project/k8s
    insertafter: 'image: angular-app'
    line: '              imagePullPolicy: IfNotPresent'

- name: Apply Kubernetes configs
  shell: kubectl apply -f /home/usr/project/k8s -n application
  become: yes
  become_user: usr
- name: Expose Application
  command: kubectl expose service angular-app --type=NodePort --target-port=80 --name=angular-app-np -n application
  become: yes
  become_user: usr