- name: Installer les dépendances pour Minikube
  apt:
    name:
      - conntrack
      - docker.io
      - curl
    state: latest

- name: Télécharger Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Installer kubectl
  get_url:
    url: https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Installer Helm
  get_url:
    url: https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz

- name: Décompresser Helm
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp
    remote_src: yes

- name: Déplacer les binaires de Helm
  command: mv /tmp/linux-amd64/helm /usr/local/bin/helm

- name: Démarrer Minikube
  command: minikube start --driver=docker
  become: yes
  become_user: usr

- name: Créer un namespace monitoring
  command: kubectl create namespace monitoring
  become: yes
  become_user: usr

- name: Ajouter le repo Helm pour Prometheus
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Mettre à jour les dépôts Helm
  command: helm repo update
  become: yes
  become_user: usr

- name: Déployer Prometheus
  command: helm install prometheus prometheus-community/prometheus --namespace monitoring
  become: yes
  become_user: usr

- name: Expose Prometheus
  command: kubectl expose service prometheus-server --type=NodePort --target-port=9090 --name=prometheus-server-np
  become: yes
  become_user: usr

- name: Ajouter le repo Helm pour Grafana
  command: helm repo add grafana https://grafana.github.io/helm-charts

- name: Déployer Grafana
  command: helm install grafana grafana/grafana --namespace monitoring
  become: yes
  become_user: usr

- name: Expose Grafana
  command: kubectl expose service grafana --type=NodePort --target-port=3000 --name=grafana-np
  become: yes
  become_user: usr