- name: Démarrer Minikube
  command: minikube start --driver=docker
  become: yes
  become_user: usr

- name: Créer un namespace monitoring
  command: kubectl create namespace monitoring
  become: yes
  become_user: usr

- name: Ajouter le repo Helm pour Prometheus
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Mettre à jour les dépôts Helm
  command: helm repo update
  become: yes
  become_user: usr

- name: Déployer Prometheus
  command: helm install prometheus prometheus-community/prometheus --namespace monitoring
  become: yes
  become_user: usr

- name: Expose Prometheus
  command: kubectl expose service prometheus-server --type=NodePort --target-port=9090 --name=prometheus-server-np --namespace=monitoring
  become: yes
  become_user: usr

- name: Wait Prometheus to run
  command: sleep 30

- name: Update services list
  command: minikube service list
  become: yes
  become_user: usr

- name: Get Prometheus url
  command: minikube service prometheus-server-np --url -n monitoring
  register: prometheus_url
  ignore_errors: yes
  become: yes
  become_user: usr

- name: Ajouter le repo Helm pour Grafana
  command: helm repo add grafana https://grafana.github.io/helm-charts

- name: Mettre à jour les dépôts Helm
  command: helm repo update
  become: yes
  become_user: usr

- name: Déployer Grafana
  command: helm install grafana grafana/grafana --namespace monitoring
  become: yes
  become_user: usr

- name: Expose Grafana
  command: kubectl expose service grafana --type=NodePort --target-port=3000 --name=grafana-np --namespace=monitoring
  become: yes
  become_user: usr

- name: Get Grafana Credential
  shell: kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode
  register: grafana_password
  args:
    executable: /bin/bash
  become: yes
  become_user: usr

- name: Get Grafana URL
  command: minikube service grafana-np --url -n monitoring
  register: grafana_url
  ignore_errors: yes
  become: yes
  become_user: usr

- name: Créer un namespace application
  command: kubectl create namespace application
  become: yes
  become_user: usr

- name: Print Grafana admin password
  debug:
    msg: "Grafana admin password is: {{ grafana_password.stdout }}"

- name: Print Grafana Credential
  debug:
    msg: "l'url de grafana est: {{ grafana_url.stdout }}"

- name: Print Prometheus Credential
  debug:
    msg: "l'url de prometheus est: {{ prometheus_url.stdout }}"

