
- name: Installer les dépendances nécessaires
  apt:
    name:
      - curl
      - docker.io
      - conntrack
    state: present
    update_cache: yes

- name: Télécharger Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Installer kubectl
  get_url:
    url: https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Config docker group
  command: echo "sudo usermod -aG docker $USER && newgrp docker"

- name: Démarrer Minikube
  command: minikube start --driver=docker

- name: Activer Metrics Server dans Minikube
  command: minikube addons enable metrics-server

- name: Déployer Prometheus
  shell: |
    kubectl create namespace monitoring || true
    kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml -n monitoring --namespace=default

- name: Déployer Grafana
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/grafana/helm-charts/main/charts/grafana/templates/deployment.yaml -n monitoring
    kubectl expose deployment grafana --type=NodePort --port=3000 -n monitoring

- name: Obtenir le NodePort de Grafana
  shell: kubectl get service grafana -n monitoring -o=jsonpath='{.spec.ports[?(@.port==3000)].nodePort}'
  register: grafana_port

- name: Afficher les informations d'accès à Grafana
  debug:
    msg: "Accédez à Grafana via http://{{ ansible_host }}:{{ grafana_port.stdout }}"
